spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: anime-service
  datasource:
    url: jdbc:mysql://localhost:3306/anime_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
threads:
  virtual:
    enabled: true

server:
  port: 8090
  servlet:
    context-path: /

  error:
    include-stacktrace: on_param

database:
  url:
  username: ${LOCAL_USERNAME}
  password: ${LOCAL_USERNAME}

